fix(deps): update all non-major dependencies (#226)
This PR contains the following updates:

| Package | Type | Update | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|---|---|
|  |  | lockFileMaintenance | All locks refreshed |  |  |  |  |
| [react-router](https://redirect.github.com/remix-run/react-router) ([source](https://redirect.github.com/remix-run/react-router/tree/HEAD/packages/react-router)) | dependencies | patch | [`7.1.1` -> `7.1.3`](https://renovatebot.com/diffs/npm/react-router/7.1.1/7.1.3) | [![age](https://developer.mend.io/api/mc/badges/age/npm/react-router/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/react-router/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/react-router/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/react-router/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [react-router-dom](https://redirect.github.com/remix-run/react-router) ([source](https://redirect.github.com/remix-run/react-router/tree/HEAD/packages/react-router-dom)) | dependencies | patch | [`7.1.1` -> `7.1.3`](https://renovatebot.com/diffs/npm/react-router-dom/7.1.1/7.1.3) | [![age](https://developer.mend.io/api/mc/badges/age/npm/react-router-dom/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/react-router-dom/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/react-router-dom/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/react-router-dom/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [sass-embedded](https://redirect.github.com/sass/embedded-host-node) | devDependencies | patch | [`1.83.1` -> `1.83.4`](https://renovatebot.com/diffs/npm/sass-embedded/1.83.1/1.83.4) | [![age](https://developer.mend.io/api/mc/badges/age/npm/sass-embedded/1.83.4?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/sass-embedded/1.83.4?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/sass-embedded/1.83.1/1.83.4?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/sass-embedded/1.83.1/1.83.4?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

🔧 This Pull Request updates lock files to use the latest dependency versions.

---

### Release Notes

<details>
<summary>remix-run/react-router (react-router)</summary>

### [`v7.1.3`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router/CHANGELOG.md#713)

[Compare Source](https://redirect.github.com/remix-run/react-router/compare/react-router@7.1.2...react-router@7.1.3)

*No changes*

### [`v7.1.2`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router/CHANGELOG.md#712)

[Compare Source](https://redirect.github.com/remix-run/react-router/compare/react-router@7.1.1...react-router@7.1.2)

##### Patch Changes

-   Fix issue with fetcher data cleanup in the data layer on fetcher unmount ([#&#8203;12681](https://redirect.github.com/remix-run/react-router/pull/12681))
-   Do not rely on `symbol` for filtering out `redirect` responses from loader data ([#&#8203;12694](https://redirect.github.com/remix-run/react-router/pull/12694))

    Previously, some projects were getting type checking errors like:

    ```ts
    error TS4058: Return type of exported function has or is using name 'redirectSymbol' from external module "node_modules/..." but cannot be named.
    ```

    Now that `symbol`s are not used for the `redirect` response type, these errors should no longer be present.

</details>

<details>
<summary>remix-run/react-router (react-router-dom)</summary>

### [`v7.1.3`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-dom/CHANGELOG.md#713)

[Compare Source](https://redirect.github.com/remix-run/react-router/compare/react-router-dom@7.1.2...react-router-dom@7.1.3)

##### Patch Changes

-   Updated dependencies:
    -   `react-router@7.1.3`

### [`v7.1.2`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-dom/CHANGELOG.md#712)

[Compare Source](https://redirect.github.com/remix-run/react-router/compare/react-router-dom@7.1.1...react-router-dom@7.1.2)

##### Patch Changes

-   Updated dependencies:
    -   `react-router@7.1.2`

</details>

<details>
<summary>sass/embedded-host-node (sass-embedded)</summary>

### [`v1.83.4`](https://redirect.github.com/sass/embedded-host-node/blob/HEAD/CHANGELOG.md#1834)

[Compare Source](https://redirect.github.com/sass/embedded-host-node/compare/1.83.3...1.83.4)

-   No user-visible changes.

### [`v1.83.3`](https://redirect.github.com/sass/embedded-host-node/blob/HEAD/CHANGELOG.md#1833)

[Compare Source](https://redirect.github.com/sass/embedded-host-node/compare/1.83.2...1.83.3)

-   No user-visible changes.

### [`v1.83.2`](https://redirect.github.com/sass/embedded-host-node/blob/HEAD/CHANGELOG.md#1832)

[Compare Source](https://redirect.github.com/sass/embedded-host-node/compare/1.83.1...1.83.2)

-   Properly display deprecation IDs for the JS Sass API.

-   Don't display deprecation IDs for user-defined deprecations.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 10am on saturday" in timezone Europe/Berlin, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://redirect.github.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/). View the [repository job log](https://developer.mend.io/github/SvenKirschbaum/md-frontend).